[project]
name = "data-engineering-course"
version = "0.3.1"
description = ""
authors = [{ name = "Xavier Lai", email = "xavier.l@cabaia.fr" }]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "requests>=2.32.3,<3.0.0",
    "google-cloud-storage>=2.18.2,<3.0.0",
    "geopy>=2.4.1,<3.0.0",
    "pandas>=2.2.3,<3.0.0",
    "pandas-gbq>=0.23.2,<0.24.0",
    "fastapi[standard]>=0.115.0,<0.116.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "pydantic>=2.9.2,<3.0.0",
    "pydantic-settings>=2.6.1,<3.0.0",
    "google-auth>=2.36.0,<3.0.0",
]

[tool.uv]
package = false
